# Generated by Django 3.1.6 on 2021-02-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileFeeItem',
            new_name='ProfileFeedItem',
        ),
    ]
